### ISSUE TITLE
Rename `Replay` config options

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-migr8#3]
Replay config options

- [x] `blockSelector` → `block`
- [x] `blockClass` → `block`
- [x] `ignoreClass` → `ignore`
- [x] `maskTextClass` → `mask`
- [x] `maskTextSelector` → `mask`
- [ ] `maskInputOptions` → `mask`

**Comment by mydea** [comment]
leaving `maskInputOptions` as there is no direct replacement - you may need to `unmask` for certain selectors instead etc.
