### ISSUE TITLE
Remove unneeded integrations & handlers

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-migr8#39]
We should remove integrations/handlers that are no longer needed, like:

`Sentry.Handlers.requestHandler()`
`Sentry.Handlers.errorHandler()`
`Sentry.Handlers.tracingHandler()`

As well as the old `Sentry.Integrations.Express()` integration.

**Comment by Lms24** [comment]
Oh I missed that this issue exists; Gonna reference it in #49

**Comment by Lms24** [comment]
Closing as we decided to archive migr8 and its unlikely that we'll further spend time on open migr8 issues.
