### ISSUE TITLE
Bump bundler plugins to latest

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-migr8#40]
We should also bump the bundler plugins, e.g. `@sentry/vite-plugin` or `@sentry/webpack-plugin`, to the latest version - as older versions may not play well with v8.

**Comment by andreiborza** [comment]
This is already handled by https://github.com/getsentry/sentry-migr8/blob/fe5d4a3ff1ee3a1d861472d689e28a4f11f6b209/src/transformers/sdkLatestVersion/index.js#L33
