### ISSUE TITLE
Running migr8 which allows to stay on v7

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-migr8#46]
### Description:

There are scenarios where migr8 cannot make all fixes necessary to make a working application with V8. The existing solution is to add to-dos

**examples:**
- where the user is instrumenting by calling the hub directly

### Solution

the codemod will apply all possible mods, and only upgrade to latest version of V7 with all deprecated APIs and replacement APIs available.

**Outcome:**
The user then is as close as possible
- mods applied where possible
- `//to-dos` added 
- SDK version updated to latest of v7

**Comment by Lms24** [comment]
Given how much time has passed since this was opened and that we'll likely stop supporting v7 when releasing v9, I think it's fair to close this issue.
