### ISSUE TITLE
migration docs incorrect: withSentry → wrapApiWithSentry 

### ISSUE THREAD

**Issue by peter-bilt** [getsentry/sentry-migr8#56]
this line in the docs is incorrect:

migration docs incorrect: withSentry → wrapApiWithSentry 

 wrapApiWithSentry  does not exist in v8 of this package

**Comment by Lms24** [comment]
Hey @peter-bilt thanks for writing and sorry for the very late reply!

You're right, `wrapApiWithSentry` doesn't exist. Instead, `withSentry` should be replaced with  `wrapApiHandlerWithSentry`. Not only is the readme/doc incorrect but also our transformer for NextJS. So I'll classify this as a migr8 bug for now. Thanks!

**Comment by Lms24** [comment]
Closing as we decided to archive migr8 and its unlikely that we'll further spend time on open migr8 issues. 
We're already working on the next major version for the SDK which will feature way less breaking changes, rendering a codemod/migration tool like migr8 unnecessary. Sorry for anyone who's running into this issue. Please follow the manual [migration guide](https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/).
