### ISSUE TITLE
`traceOrigins` and `tracePropagationTargets` should be lifted out of browser tracing integrations

### ISSUE THREAD

**Issue by andreiborza** [getsentry/sentry-migr8#59]
Previously, `traceOrigins` and `tracePropagationTragets` were set on browser tracing integrations, e.g.

```js
Sentry.reactRouterV6BrowserTracingIntegration({
      tracingOrigins: tracingOrigins,
      tracePropagationTargets: tracingOrigins,
      useEffect,
      useLocation,
      useNavigationType,
      createRoutesFromChildren,
      matchRoutes,
    }),
```

These should be lifted up into the client options.

**Comment by Lms24** [comment]
There already is a transformer that takes care of this generally: https://github.com/getsentry/sentry-migr8/commit/cbcdbc2aad37e5486b84d52a5748c4eb317d25f1 

However, this only works for specific v7-style integrations, most prominantly `new BrowserTracing({...})`. If we fix this, we should adjust the guard to account for newer integration functions as well.

**Comment by Lms24** [comment]
Closing as we decided to archive migr8 and it's unlikely that we'll further spend time on open migr8 issues. 
We're already working on the next major version for the SDK which will feature way less breaking changes, rendering a codemod/migration tool like migr8 unnecessary.
