### ISSUE TITLE
Automatically add `instrumentation.ts` for Next.js projects

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-migr8#67]
Ran into this while upgrading `sentry.engineering`: https://github.com/getsentry/sentry.engineering/pull/139

**Comment by Lms24** [comment]
Closing as we decided to archive migr8 and it's unlikely that we'll further spend time on open migr8 issues.
We're already working on the next major version for the SDK which will feature way less breaking changes, rendering a codemod/migration tool like migr8 unnecessary.
