### ISSUE TITLE
Running migr8 on a svelte project updates all self-closing components and tags to be explicitly closed

### ISSUE THREAD

**Issue by fnimick** [getsentry/sentry-migr8#68]
### Environment

`@sentry/migr8@latest`

### Steps to Reproduce

1. Create a svelekit project
2. Run `@sentry/migr8` on it, using any transform option (from my testing, it appears that all transformers that use `jscodeshift` will do this)
3. Notice that all files have been updated to move self-closing components to explicitly closed components. 

### Expected Result

Code unrelated to sentry should not be modified.

### Actual Result

All components and tags were changed, example:
```
diff --git a/src/lib/components/InternalOnly.svelte b/src/lib/components/InternalOnly.svelte
index 27bcdcc..9a430e5 100644
--- a/src/lib/components/InternalOnly.svelte
+++ b/src/lib/components/InternalOnly.svelte
@@ -10,7 +10,7 @@
   <div class="container">
     <div class="variant-ringed-destructive relative rounded-md">
       <div class="p-3">
-        <slot />
+        <slot></slot>
       </div>
       <h2 class="absolute left-1/2 top-0 flex -translate-x-1/2 -translate-y-1/2 transform">
         <span class="bg-muted px-2 text-sm">Internal Users Only</span>
```

This affects nearly every svelte file in our codebase and is far too extensive to manually reconcile.

**Comment by Lms24** [comment]
Hey @fnimick thx for raising this issue. This was brought up before in other channels, so I just opened #69 to ignore svelte files for now. Chances are rather slim that Sentry code is added to svelte files, so I think it's fine.
